services:
  - name: perso-2026a-HLKellermann
    type: web
    runtime: docker
    plan: free
    dockerfilePath: ./Dockerfile
    dockerContext: .
    healthCheckPath: /healthz
    autoDeployTrigger: commit
    buildFilter:
      paths:
        - Dockerfile
        - render.yaml
        - app/**
        - perso-2026a-HLKellermann.cabal
      ignoredPaths:
        - README.md
        - assets/**
        - dist-newstyle/**